FROM melopt/mkdocs
LABEL maintainer="Jake Davies jake.davies@play.company"

COPY action.sh /action.sh

WORKDIR /docs

RUN echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories

RUN pip install awscli

RUN apk add --no-cache bash nodejs npm && chmod +x /action.sh
RUN npm install -g typescript typedoc


ENTRYPOINT ["/action.sh"]
