FROM squidfunk/mkdocs-material:5.1.0
LABEL maintainer="Michael Hausenblas, hausenbl@amazon.com"

COPY action.sh /action.sh

RUN echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories

RUN pip install awscli

RUN apk add --no-cache bash && chmod +x /action.sh


ENTRYPOINT ["/action.sh"]
