FROM melopt/mkdocs

COPY action.sh /action.sh

WORKDIR /docs

RUN echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories

RUN pip install -U pip setuptools wheel
RUN pip install -U awscli mkdocs-material mdx_truly_sane_lists

RUN apk add --no-cache bash nodejs npm && chmod +x /action.sh
RUN npm install -g github-release-notes


ENTRYPOINT ["/action.sh"]
